"""empty message

Revision ID: e7b2d12e8b01
Revises: 
Create Date: 2021-06-02 00:41:46.448239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b2d12e8b01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=64), nullable=False),
    sa.Column('teacing', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('lunch', sa.String(length=32), nullable=False),
    sa.Column('pretest', sa.Integer(), nullable=False),
    sa.Column('posttest', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=64), nullable=False),
    sa.Column('n_student', sa.Integer(), nullable=False),
    sa.Column('settting', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school')
    op.drop_table('student')
    # ### end Alembic commands ###
